### ISSUE TITLE
SMTP account

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/SignIn#21]
The SMTP account from `starcounter.io`:

```
wordpress@starcounter.com
mail.your-server.de
```

Does not access mails:

```
"System.Net.Mail.SmtpFailedRecipientException: Mailbox unavailable. The server response was: relay not permitted
   at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at SignIn.RestorePasswordFormPage.SendNewPassword(String Name, String Username, String NewPassword, String Email) in C:\GitHub\Samples\SignIn\src\SignIn\ViewModels\RestorePasswordFormPage.json.cs:line 62
   at SignIn.RestorePasswordFormPage.Handle(RestoreClick Action) in C:\GitHub\Samples\SignIn\src\SignIn\ViewModels\RestorePasswordFormPage.json.cs:line 43
   at SignIn.RestorePasswordFormPage.JsonByExample.Schema.<>c.<.ctor>b__0_11(Json pup, Input`1 input) in C:\GitHub\Samples\SignIn\src\SignIn\obj\x64\Debug\ViewModels\RestorePasswordFormPage.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 225
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 247
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 105
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 36
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 650
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 491
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 56
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-262\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 777
FailedRecipient=<admin@starcounter.com>
HResult=-2146233088
"
```

**Comment by miyconst** [comment]
cc @warpech

**Comment by warpech** [comment]
I created new credentials that work for me (tested locally from Node.js).

But for some reason, it does not deliver to @starcounter.com. It delivers OK to @gmail.com

```js
var transporter = nodemailer.createTransport({
    host: 'mail.your-server.de',
    port: 465,
    auth: {
        user: 'signinapp@starcounter.io',
        pass: 'XXXXXXX'
    },
    secure: true
});
```

I will send you the password on IM.

**Comment by warpech** [comment]
I this server does not gain Microsoft Office 365's trust, maybe it is better if we switch to an SMTP account at gmail. Let's give it few more hours.

**Comment by warpech** [comment]
The following setup seems to be recommended:

```js
var transporter = nodemailer.createTransport({
    host: 'mail.your-server.de',
    port: 587,
    auth: {
        user: 'signinapp@starcounter.io',
        pass: 'XXXXXXX'
    },
    secure: false,
    requireTLS: true
});
```

(but still, I don't receive email from it at starcounter.com :( )

**Comment by warpech** [comment]
I know what is going on. SMTP at starcounter.io is thinking that the mail server at starcounter.com is also hosted on Hetzner, which it is not. I will write a question to the admin at Hetzner about this.

**Comment by warpech** [comment]
I wrote a question to Hetzner's admin about this

**Comment by miyconst** [comment]
@warpech thanks for taking care of this.

**Comment by miyconst** [comment]
>The following setup seems to be recommended:

The setup provided works for me. Emails received, thank you.

**Comment by warpech** [comment]
After applying instructions from Hetzner, emails are also delivered OK to mailboxes @starcounter.com
